language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='nightly'
  - TEST_COMMAND=bench EXTRA_FLAGS='' FEATURES='nightly bench'
  - TEST_COMMAND=build EXTRA_FLAGS='--verbose' FEATURES='nightly' 

matrix:
  exclude:
    # Currently, we only support nightly.
    - rust: stable
      env: TEST_COMMAND=bench EXTRA_FLAGS='' FEATURES='nightly bench'
    - rust: beta
      env: TEST_COMMAND=bench EXTRA_FLAGS='' FEATURES='nightly bench'
    - rust: stable
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='nightly'
    - rust: beta
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='nightly'
    - rust: stable
      env: TEST_COMMAND=build EXTRA_FLAGS='--verbose' FEATURES='nightly'
    - rust: beta
      env: TEST_COMMAND=build EXTRA_FLAGS='--verbose' FEATURES='nightly'

script:
- cargo $TEST_COMMAND --features="$FEATURES" $EXTRA_FLAGS
