[package]
name = "sidh"
version = "0.1.0"
authors = ["Erkan Tairi <erkan.tairi@gmail.com>"]

[build-dependencies]
cc = "1.0.3"
subtle = "^0.3"

[dependencies.quickcheck]
version = "0.5"

[dependencies.rand]
version = "0.3"

[dependencies.subtle]
version = "^0.3"
default-features = false
